base_config: ./base.yaml
task_cls: tasks.vocoder.hifigan.HifiGanTask
resblock: "1"
adam_b1: 0.8
adam_b2: 0.99
upsample_rates: [ 8,8,2,2 ]
upsample_kernel_sizes: [ 16,16,4,4 ]
upsample_initial_channel: 512
resblock_kernel_sizes: [ 3,7,11 ]
resblock_dilation_sizes: [ [ 1,3,5 ], [ 1,3,5 ], [ 1,3,5 ] ]

use_pitch_embed: false
use_fm_loss: false
use_ms_stft: false

lambda_mel: 5.0
lambda_mel_adv: 1.0
lambda_cdisc: 4.0
lambda_adv: 1.0

lr: 0.0002            # Generator's learning rate.
generator_scheduler_params:
  step_size: 600
  gamma: 0.999
discriminator_scheduler_params:
  step_size: 600
  gamma: 0.999
max_updates: 3000000